### ISSUE TITLE
Reference point for startTime?

### ISSUE THREAD

**Issue by gi11es** [WICG/element-timing#1]
What's the point in time used for "0" in startTime? The description doesn't say.

In Chrome 75's implementation, when I look it up on the performance timeline, experimenting locally with disabled cache and a throttled connection, I always get 0 for startTime for above-the-fold images. When clearly I see that they didn't download and render instantly during the pageload.

**Comment by maxlgu** [comment]
0 means null here. For non-zero cases, they are absolute time. For example, when we have performance.timing.navigationStart===1552932345429, new Date(performance.timing.navigationStart) will give us the formatted date and time, i.e., Mon Mar 18 2019 14:05:45 GMT-0400 (Eastern Daylight Time).

**Comment by npm1** [comment]
The way our timestamps are handled is explained in more detail here: https://w3c.github.io/hr-time/#sec-domhighrestimestamp

Basically, the timestamp is a monotonic timestamp relative to the time origin. Does that answer the question?

**Comment by npm1** [comment]
Regarding getting 0 for some images, it is probably because they do not pass the Timing Allow Origin check.

**Comment by gi11es** [comment]
Indeed, Timing-Allow-Origin was missing, adding it fixed it. Makes complete sense, but might be worth mentioning in the explainer briefly.

**Comment by npm1** [comment]
Which explainer are you looking at? I see this mentioned in the 'Origin restrictions' section of the GitHub explainer.

**Comment by gi11es** [comment]
Oh, well, I'm definitely blind.
