### ISSUE TITLE
ResourceTiming's responseEnd is earlier than image real render complete time

### ISSUE THREAD

**Issue by xcodebuild** [WICG/element-timing#11]
> responseEnd: for images, the timestamp of when the last byte of the resource response was received, same as ResourceTiming's responseEnd

Take a example, when I take a profile with devtools in https://www.google.com with `CPU 6x slow down`,

![image](https://user-images.githubusercontent.com/5436704/58749553-0b4eae00-84ba-11e9-96f6-89b0ad7e5b8c.png)
![image](https://user-images.githubusercontent.com/5436704/58749556-10136200-84ba-11e9-80a7-c4bc4043a155.png)

The google logo image dose not start paint until **753ms**, but the `responseEnd` in ResourceTiming's is **415ms**, which is earlier than paint time.

![image](https://user-images.githubusercontent.com/5436704/58749570-405b0080-84ba-11e9-86ac-1506bb6dbd9e.png)

On the other hand, if we use a preload link to preload image such as

```html
<link rel="preload" as="image" src="xxx.png">
```

The `responseEnd` of this link will be even more earlier.

**So should we just use image render end time instead of ResourceTiming's responseEnd here?**

**Comment by npm1** [comment]
The `startTime` is the image rendering time. However, for security reasons we can only expose such a timestamp in certain cases (when the image passes the Timing Allow Origin check). This is why we also expose `responseEnd`, which can be used as a replacement for images for which the rendering timestamp cannot be exposed. Does this make sense? Let me know if I can close this issue.

**Comment by xcodebuild** [comment]
Is `startTime` image rendering start time or rendering end time? Sometimes image may take a long time to finish rendering.

**Comment by npm1** [comment]
It is the rendering time of the image after it is fully loaded. So I would say it's closer to 'rendering end time' but I'm not entirely sure what you mean by that.
