### ISSUE TITLE
`naturalWidth` and `naturalHeight`?

### ISSUE THREAD

**Issue by yoavweiss** [WICG/element-timing#12]
Is there a particular reason for exposing the natural width and height of an image, rather than exposing its displayed width and height? I think the latter is more relevant.

**Comment by tdresser** [comment]
We're viewing this as a very rough proxy for "information density", in a way. It's reasonably common to see small images scaled up to be huge (or repeated a bunch), but those cases are rarely important.

We could consider exposing both sizes.

**Comment by npm1** [comment]
What do you mean both sizes? The display size can already be computed from the intersectionRect

**Comment by tdresser** [comment]
Not if it's clipped by the viewport, right?

I'm not sure there's a usecase there though.

**Comment by npm1** [comment]
I wouldn't call something outside of the viewport to count for its 'displayed' width/height.

**Comment by tdresser** [comment]
Fair point!

**Comment by yoavweiss** [comment]
OK, fair enough.
