### ISSUE TITLE
The "elementtiming" attribute + "smaller than 15% of the viewport size" check appears wrong

### ISSUE THREAD

**Issue by foolip** [WICG/element-timing#18]
https://wicg.github.io/element-timing/#sec-report-text says:
> If element’s elementtiming attribute getter returns a DOMString of zero length and if intersectionRect’s size is smaller than 15% of the viewport size, then abort these steps.

The *and* here seems to be a mistake, since it means that the "elementtiming" attribute doesn't need to be present. Probably each condition should be enforced separately.

**Comment by foolip** [comment]
@npm1 this was closed by https://github.com/WICG/element-timing/pull/19, but can you confirm that it was a mistake? Is the same mistake in Chromium? (I couldn't find the 15% check in code search.)

**Comment by npm1** [comment]
Yep the 15% was removed from image but not from text. Originally we had the idea of implicit registration based on size but we did some research and decided to remove it. I'll remove the 15% from text now.
