### ISSUE TITLE
Definition of `identifier` and `id` IDL attributes don't match Chromium

### ISSUE THREAD

**Issue by foolip** [WICG/element-timing#20]
https://wicg.github.io/element-timing/#sec-performance-element-timing says:

> The identifier attribute’s getter must return element’s elementtiming attribute value.

and

> The id attribute’s getter must return element’s id attribute value.

In other words, if the "elementtiming" or "id" content attributes change, this should be reflected in these IDL attributes. In Chromium, they are initialized when `PerformanceElementTiming` is created and never change:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/timing/performance_element_timing.h?l=69&rcl=82aeb2ab83210df04da360f1bb8b9e9095e51085

**Comment by foolip** [comment]
https://wicg.github.io/largest-contentful-paint/#sec-largest-contentful-paint-interface doesn't have the same issue, there `id` and `url` are copied on creation.

**Comment by npm1** [comment]
Yep, we should copy the values on creation, thanks for filing the issue!
