### ISSUE TITLE
Should text and image have different entryType

### ISSUE THREAD

**Issue by npm1** [WICG/element-timing#4]
From the TAG [review](https://github.com/w3ctag/design-reviews/issues/326), worth thinking which option is better:

* A single entryType 'element'.
* Two entryType values: 'image' and 'text'.

**Comment by tdresser** [comment]
We should clearly indicate image vs text somehow.

If we go with image & text, I think:
- first-paint
- first-contentful-paint
- image-paint
- text-paint

is probably the clearest way to name things?

**Comment by npm1** [comment]
"first-paint" and "first-contentful-paint" are the `name` values, the `entryType` values are "paint". So under that reasoning, we should do:
* Keep `entryType` as "element"
* Set the `name` to something differentiating image and text. Right now, `name` is used for images as the URL (and for text, as some characters). But this information could be moved to a different attribute.

**Comment by npm1** [comment]
This is done.
