### ISSUE TITLE
Starting point shift with countering transform change should be ignored

### ISSUE THREAD

**Issue by wangxianzhu** [WICG/element-timing#55]
Test case:
https://chromium-review.googlesource.com/c/chromium/src/+/2673965/6/third_party/blink/web_tests/external/wpt/layout-instability/transform-counter-layout-shift.html

This is a pattern used in many websites containing carousal UI which
- moves elements smoothly using transform
- and new contents to be shifted in, the original transform is replaced by a layout offset, without any visual change

**Comment by npm1** [comment]
Did you mean to file this in Layout Instability spec? This is Element Timing

**Comment by wangxianzhu** [comment]
Oops, sorry. Not sure how I reached here. Perhaps an extra click on a link to element-timing in the layout instability doc caused this.
