### ISSUE TITLE
Improve definition of "associated element"

### ISSUE THREAD

**Issue by npm1** [WICG/element-timing#8]
Figure out a better way to match requests / responses (and in general resources) with elements. Right now, it is not properly defined.

**Comment by xcodebuild** [comment]
Maybe we need some infomation in `elementtiming`? Such as 

```html
<img elementtiming="this_is_id"></img>
```

then use `id` instead of image url in `name`. 

Multiple image element with same image url would have different render timing.

**Comment by xcodebuild** [comment]
Sorry I have not notice `identifier` is already there.

> identifier: the value of the elementtiming attribute of the element.

**Comment by npm1** [comment]
To be clear, this issue is to track a spec problem and not really something related to what is exposed to developers. But yes we have elementtiming and id values :)

**Comment by npm1** [comment]
Closing this bug because 'associated element' is no longer a thing.
